# Generated by Django 4.0.4 on 2022-06-01 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile_user_follow_profile_value_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_follow',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
